// src/components/layout/ContentPanel.tsx
import { FunctionComponent, useMemo } from "react";

import { GithubRepositoryMeta } from "@/api/fetcher";
import { SidePanelSelectableCategory } from "./Navbar";
import { ProjectCard, ProjectMeta } from "./ProjectCard";

export type GithubProjectMeta = GithubRepositoryMeta & {
  blogPostSlug: string | null;
};

interface ContentPanelProps {
  githubProjects: readonly GithubProjectMeta[];
  highlightContentCategory: SidePanelSelectableCategory | null;
}

const ContentPanel: FunctionComponent<ContentPanelProps> = ({ githubProjects, highlightContentCategory }) => {
  // Content gathering and processing
  const content = useMemo<ProjectMeta[]>(
    () =>
      githubProjects.map(rawItem => ({
        type: "github",
        url: rawItem.url,
        title: rawItem.name,
        githubFullName: rawItem.fullName,
        description: rawItem.description ?? "",
        githubForksCount: rawItem.forksCount,
        githubStars: rawItem.stargazersCount ?? 0,
        blogPostSlug: rawItem.blogPostSlug,
      })),
    [githubProjects],
  );

  const highlighted = highlightContentCategory === "projects";

  // Content rendering
  return (
    <div className="grid gap-4 pb-4 md:grid-cols-3">
      {content.map(projectMeta => (
        <ProjectCard key={projectMeta.githubFullName} highlighted={highlighted} projectMeta={projectMeta} />
      ))}
    </div>
  );
};

export default ContentPanel;

// src/lib/ContentPanel.svelte
<script context="module" lang="ts">
  import type { ProjectMeta } from "./ProjectCard.svelte";
  import type { GithubRepositoryMeta } from "../api/fetcher";
  import type { SidePanelSelectableCategory } from "./Navbar.svelte";

  export type GithubProjectMeta = GithubRepositoryMeta & {
    blogPostSlug: string | null;
  };
</script>

<script lang="ts">
  import ProjectCard from "./ProjectCard.svelte";

  export let githubProjects: readonly GithubProjectMeta[];
  export let highlightContentCategory: SidePanelSelectableCategory;

  $: content = ((): readonly ProjectMeta[] => githubProjects.map(githubProject => ({
    type: "github",
    url: githubProject.url,
    title: githubProject.name,
    githubFullName: githubProject.fullName,
    description: githubProject.description ?? "",
    githubForksCount: githubProject.forksCount,
    githubStars: githubProject.stargazersCount ?? 0,
    blogPostSlug: githubProject.blogPostSlug,
  })))();
  $: highlighted = highlightContentCategory === "projects";
</script>

<div class="grid grid-cols-1 gap-4 pb-4 lg:grid-cols-2">
  {#each content as projectMeta}
    <ProjectCard {highlighted} {projectMeta} />
  {/each}
</div>
