// src/components/ExternalLink.tsx
import { FunctionComponent, HTMLAttributeAnchorTarget, ReactNode, useMemo } from "react";

interface ExternalLinkProps {
  href: string;
  newTab?: boolean;
  children: ReactNode;
}

export const ExternalLink: FunctionComponent<ExternalLinkProps> = ({
  href,
  newTab = true,
  children,
}) => {
  const target = useMemo((): HTMLAttributeAnchorTarget => newTab ? "_blank" : "_self", [newTab]);
  return (
    <a href={href} target={target} rel="noopener noreferrer" className="no-underline">
      {children}
    </a>
  );
};

// src/lib/ExternalLink.svelte
<script lang="ts">
  export let href: string;
  export let label: string;
  export let inNewTab = true;

  $: target = inNewTab ? "_blank" : "_self";
</script>

<a {href} {target} rel="noopener noreferrer">
  {label}
</a>

<style lang="postcss">
  a {
    @apply no-underline text-white font-semibold;
  }
</style>
