// src/components/layout/Navbar.tsx
import clsx from "clsx";
import Link from "next/link";
import { FunctionComponent } from "react";

import { ExternalLink } from "../ExternalLink";

interface NavbarLinkProps {
  href: string;
  label: string;
  selected: boolean;
}

const NavbarLink: FunctionComponent<NavbarLinkProps> = ({ href, label, selected }) => (
  <li className="mr-8 last:mr-0">
    <Link href={href} className={clsx("cursor-pointer hover:text-lychee", selected ? "text-lychee" : "text-white")}>
      {label}
    </Link>
  </li>
);

export const navigationSelectableCategories = ["projects", "blog", "about"] as const;
export type NavigationSelectableCategory = typeof navigationSelectableCategories[number];

interface NavbarProps {
  category: NavigationSelectableCategory;
}

export const Navbar: FunctionComponent<NavbarProps> = ({ category }) => (
  <div className="flex flex-col">
    <div className="w-full flex justify-center items-center mr-12 font-bold py-6">
      <Link href="/">
        newstackwhodis
      </Link>
    </div>
    <div className="w-full flex flex-col md:flex-row self-center items-center justify-between">
      <div />
      <header className="flex items-center p-2 max-w-3xl mx-auto text-gray-lighter md:text-xl">
        <nav className="flex items-center flex-grow">
          <ul className="flex items-center flex-grow md:text-xl">
            <NavbarLink href="/" label="Projects" selected={category === "projects"} />
            <NavbarLink href="/blog" label="Blog" selected={category === "blog"} />
            <NavbarLink href="/blog/about" label="About" selected={category === "about"} />
          </ul>
        </nav>
      </header>
      <div className={clsx("font-semibold py-2 md:py-0", category === "blog" && "opacity-0")}>
        <ExternalLink href="https://github.com/pierreyoda/newstackwhodis">
          GitHub
        </ExternalLink>
      </div>
    </div>
  </div>
);

// src/lib/Navbar.svelte
<script lang="ts">
  import NavbarLink from "./NavbarLink.svelte";
  import ExternalLink from "./ExternalLink.svelte";
  import type { NavigationSelectableCategory } from "./types";

  export let selectedCategory: NavigationSelectableCategory;

  $: hideGitHubLink = selectedCategory === "blog";
  $: githubLinkContainerClasses = hideGitHubLink ? "github-link-container hidden" : "github-link-container";
</script>

<div class="outer-container">
  <div class="w-full justify-center flex items-center mr-12 text-white font-bold py-6">
    <a data-sveltekit-prefetch href="/">
      newstackwhodis (Work In Progress)
    </a>
  </div>
  <div class="container">
    <div />
    <div class="navbar-container">
      <nav>
        <ul class="flex items-center flex-grow md:text-xl">
          <NavbarLink href="/" label="Projects" isSelected={selectedCategory === "projects"} />
          <NavbarLink href="/blog" label="Blog" isSelected={selectedCategory === "blog"} />
          <NavbarLink href="/blog/about" label="About" isSelected={selectedCategory === "about"} />
        </ul>
      </nav>
    </div>
    <div class={githubLinkContainerClasses}>
      <ExternalLink href="https://github.com/pierreyoda/newstackwhodis">
        GitHub
      </ExternalLink>
    </div>
  </div>
</div>

<style lang="postcss">
  .outer-container {
    @apply flex flex-col;
  }

  .container {
    @apply w-full flex flex-col self-center items-center justify-between;
  }

  .navbar-container {
    @apply flex items-center p-2;
    @apply max-w-3xl mx-auto;
    @apply text-gray-lighter;

    nav {
      @apply flex items-center flex-grow;
    }
  }

  .github-link-container {
    @apply text-white font-semibold py-2;
  }

  @screen md {
    .container {
      @apply flex-row;
    }

    .navbar-container {
      nav {
        @apply text-xl;
      }
    }

    .github-link-container {
      @apply py-0;
    }
  }
</style>
