// src/components/layout/SidePanel.tsx
import { FunctionComponent } from "react";
import Link from "next/link";
import clsx from "clsx";

import { siteName, copyrightNotice } from "@/content/branding";

export const sidePanelSelectableCategories = ["blog", "projects", "about"] as const;
export type SidePanelSelectableCategory = typeof sidePanelSelectableCategories[number];

const SidePanelLink: FunctionComponent<{
  href: string;
  label: string;
  selected: boolean;
}> = ({ href, label, selected }) => (
  <div className={clsx("mt-8 text-white hover:text-lychee", selected && "text-lychee")}>
    <Link href={href}>{label}</Link>
  </div>
);

interface SidePanelProps {
  selected: SidePanelSelectableCategory | null;
}

const SidePanel: FunctionComponent<SidePanelProps> = ({ selected }) => (
  <div className="flex flex-col w-1/3 p-3 text-white bg-black md:p-12">
    <div className="flex">
      <h2 className="text-3xl">{siteName}</h2>
    </div>
    <div className="flex-col justify-between flex-grow">
      <SidePanelLink href="/" label="Projects" selected={selected === "projects"} />
      <SidePanelLink href="/blog/about/" label="About" selected={selected === "about"} />
    </div>
    <footer className="flex items-center justify-center text-sm text-gray-200">
      <span>{copyrightNotice}</span>
    </footer>
  </div>
);

export default SidePanel;

// src/lib/SidePanel.svelte
<script context="module" lang="ts">
  export const sidePanelSelectableCategories = ["blog", "projects", "about"] as const;
  export type SidePanelSelectableCategory = typeof sidePanelSelectableCategories[number];
</script>

<script lang="ts">
  import NavbarLink from "./SidePanelLink.svelte";
  import { copyrightNotice } from "../content/branding";

  export let selectedCategory: SidePanelSelectableCategory;
</script>

<div class="side-panel-container">
  <div class="flex items-center mr-8 md:mr-0">
    <img class="w-32 h-auto md:w-64" src="/brand.svg" alt="Praca logo" />
  </div>
  <nav>
    <ul class="flex items-center flex-grow md:justify-start md:flex-col md:text-xl">
      <NavbarLink href="/" label="Projects" isSelected={selectedCategory === "projects"} />
      <NavbarLink href="/blog/about" label="About" isSelected={selectedCategory === "about"} />
    </ul>
  </nav>
  <footer>
    <span>{copyrightNotice}</span>
  </footer>
</div>

<style lang="postcss">
  .side-panel-container {
    @apply flex items-center flex-shrink-0 md:flex-col md:w-1/3 md:p-12;
    @apply w-full p-3;
    @apply text-white bg-black;

    footer {
      @apply hidden items-center justify-center md:flex;
      @apply text-gray;
    }
  }
</style>
