// src/app/layout.tsx
import type { Metadata } from "next";
import { headers } from "next/headers";
import { Analytics } from "@vercel/analytics/react";

import "./globals.css";
import { Footer } from "@/components/layout/Footer";
import { Navbar, NavigationSelectableCategory } from "@/components/layout/Navbar";

export const metadata: Metadata = {
  title: "newstackwhodis",
  description: "pierreyoda's awesome tech blog",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = headers().get("x-pathname") ?? "/";
  const category: NavigationSelectableCategory = path === "/blog/about" ? "about" : path.startsWith("/blog") ? "blog" : "projects";
  return (
    <html lang="en" className="h-full bg-black-darker">
      <body className="font-sans antialiased flex flex-col w-full h-full">
        <Navbar category={category} />
        <main className="flex-grow px-2 pt-2 overflow-auto md:px-0">
          {children}
        </main>
        <Footer />
        <Analytics mode="auto" />
      </body>
    </html>
  );
};

// src/routes/__layout.svelte
<script context="module" lang="ts">
  import type { Load } from "@sveltejs/kit";

  export const load: Load = async ({ page: { path } }) => ({
    props: {
      selectedCategory: ((): NavigationSelectableCategory =>
        path === "/blog/about" ? "about" : path.startsWith("/blog") ? "blog" : "projects")(),
    },
  });
</script>

<script lang="ts">
  import "../app.css";
  import Navbar from "$lib/Navbar.svelte";
  import Footer from "$lib/Footer.svelte";
  import type { NavigationSelectableCategory } from "$lib/Navbar.svelte";

  export let selectedCategory: NavigationSelectableCategory;
</script>

<div class="layout-container">
  <div class="flex flex-col flex-grow w-full">
    <Navbar {selectedCategory} />
    <main class="flex-grow px-2 pt-2 overflow-auto md:px-8">
      <slot />
    </main>
    <Footer />
  </div>
</div>

<style lang="postcss">
  :global(html, body, #svelte) {
    @apply h-full bg-black-darker;
  }
  :global(#svelte) {
    @apply font-sans antialiased;
  }

  .layout-container {
    @apply flex flex-col w-full h-full;
    @apply max-w-3xl mx-auto;
  }
</style>
