// src/lib/lsystems/LSystemDescriptorWidget.svelte
<script lang="ts">
  import type { LSystemAlphabetConstant, LSystemAlphabetVariable, LSystemDescriptor } from "./lsystem";

  export let descriptor: LSystemDescriptor<string>;

  $: constants = Object.entries(descriptor.rules).filter(([_, { type }]) => type === "constant") as [
    string,
    LSystemAlphabetConstant,
  ][];
  $: variables = Object.entries(descriptor.rules).filter(([_, { type }]) => type === "variable") as [
    string,
    LSystemAlphabetVariable,
  ][];
</script>

<div class="container">
  <p class="name">{descriptor.name}</p>
  <p class="axiom">Axiom: {descriptor.axiom}</p>
  {#if constants.length > 0}
    <div class="section">
      <p>Constants:</p>
      <ul>
        {#each constants as constant}
          <li><span class="letter">{constant[0]}</span>: {constant[1].description}</li>
        {/each}
      </ul>
    </div>
  {/if}
  <div class="section">
    <p>Variables:</p>
    <ul>
      {#each variables as variable}
        <li><span class="letter">{variable[0]}</span> => {variable[1].production}</li>
      {/each}
    </ul>
  </div>
</div>

<style lang="postcss">
  .container {
    @apply rounded p-3;
    @apply bg-white text-black-lighter;
    .name {
      @apply text-lg font-semibold;
      @apply border-b border-lychee mb-2;
    }
    .section {
      @apply mt-2;
      p {
        @apply mb-2;
      }
      ul > li {
        @apply mb-1 text-sm;
        .letter {
          @apply text-space-blue font-semibold;
        }
      }
    }
  }
</style>

// src/components/blog/lsystem/LSystemDescriptorWidget.tsx
import { FunctionComponent, useMemo } from "react";

import { LSystemAlphabetConstant, LSystemAlphabetVariable, LSystemDescriptor } from "@/content/lsystem/lsystem";

interface LSystemDescriptorWidgetProps {
  descriptor: LSystemDescriptor<string>;
}

type LSystemAlphabetDescription = {
  constants: readonly [string, LSystemAlphabetConstant][];
  variables: readonly [string, LSystemAlphabetVariable][];
};

export const LSystemDescriptorWidget: FunctionComponent<LSystemDescriptorWidgetProps> = ({ descriptor }) => {
  const { constants, variables } = useMemo(
    () =>
      Object.entries(descriptor.rules).reduce(
        (acc: LSystemAlphabetDescription, [letter, description]): LSystemAlphabetDescription =>
          description.type === "constant"
            ? {
                constants: [...acc.constants, [letter, description]],
                variables: acc.variables,
              }
            : {
                constants: acc.constants,
                variables: [...acc.variables, [letter, description]],
              },
        {
          constants: [],
          variables: [],
        } as LSystemAlphabetDescription,
      ),
    [descriptor.rules],
  );

  return (
    <div className="lsystem-descriptor-container rounded bg-white p-3 text-black-lighter">
      <p className="mb-2 border-b border-lychee text-lg font-semibold">{descriptor.name}</p>
      <p>Axiom: {descriptor.axiom}</p>
      {constants.length > 0 && (
        <div className="section">
          <p>Constants:</p>
          <ul>
            {constants.map(([letter, constant]) => (
              <li key={letter}>
                <span className="letter">{letter}</span>:&nbsp;
                {constant.description}
              </li>
            ))}
          </ul>
        </div>
      )}
      <div className="section">
        <p>Variables:</p>
        <ul>
          {variables.map(([letter, variable]) => (
            <li key={letter}>
              <span className="letter">{letter}</span> =&gt;:&nbsp;
              {variable.production}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};
