// src/lib/ProjectCard.svelte
<script context="module" lang="ts">
  export interface ProjectMeta {
    type: "github";
    url: string;
    title: string;
    githubFullName: string;
    description: string;
    githubForksCount: number;
    githubStars: number;
    blogPostSlug: string | null;
  }
</script>

<script lang="ts">
  import ProjectTag from "$lib/ProjectTag.svelte";
  import { tagsPerProject } from "../api/github/project-tags";
  import type { ProjectTagType } from "../api/github/project-tags";

  export let isHighlighted: boolean;
  export let projectMeta: ProjectMeta;

  $: projectTags = ((): readonly ProjectTagType[] => tagsPerProject[projectMeta.githubFullName] ?? [])()
</script>

<div class="project-card-container" class:highlighted="{isHighlighted}">
  <h2 class="project-card-title" class:has-blog-post="{!!projectMeta.blogPostSlug}">
    {#if projectMeta.blogPostSlug}
      <a sveltekit:prefetch href={`/blog/${projectMeta.blogPostSlug}`}>
        {projectMeta.title}
      </a>
    {:else}
      {projectMeta.title}
    {/if}
  </h2>
  <p class="project-card-description">{projectMeta.description}</p>
  <div class="project-card-tags">
    {#each projectTags as tag}
      <ProjectTag {tag} extraClass="mr-2" />
    {/each}
  </div>
  <div class="project-card-content">
    <div class="project-card-github-link">
      <a href={projectMeta.url} target="_blank" rel="nofollow noopener noreferrer">
        View on GitHub
      </a>
    </div>
    <div class="project-card-github-stats">
      {#if projectMeta.githubForksCount > 0}
        <p class="mr-4 text-orange">
          {projectMeta.githubForksCount} fork{projectMeta.githubForksCount > 1 ? "s" : ""}
        </p>
      {/if}
      {#if projectMeta.githubStars > 0}
        <p class="text-yellow">
          {projectMeta.githubStars} star{projectMeta.githubStars > 1 ? "s" : ""}
        </p>
      {/if}
    </div>
  </div>
</div>

<style lang="postcss">
  .project-card-container {
    @apply flex flex-col items-start justify-around;
    @apply p-3 border border-gray-lighter;

    .project-card-title {
      @apply text-lg font-bold text-white;
      @apply border-b-2 border-lychee;
      &.has-blog-post:hover {
        @apply text-lychee;
      }
    }

    .project-card-description {
      @apply py-5 text-sm text-white;
    }

    .project-card-tags {
      @apply flex flex-wrap items-center w-full py-2;
    }

    .project-card-content {
      @apply flex items-center justify-between w-full text-sm;

      .project-card-github-link {
        @apply font-bold text-white rounded;
        a:hover {
          @apply text-lychee;
        }
      }

      .project-card-github-stats {
        @apply flex items-center font-semibold;
      }
    }
  }

  @screen md {
    .project-card-container {
      @apply rounded-lg;
    }
  }
</style>

// src/components/ProjectCard.tsx
import { FunctionComponent, useMemo } from "react";

import { ProjectTag } from "./ProjectTag";
import { ExternalLink } from "./ExternalLink";
import { GithubWhiteListedRepository } from "@/api/github/whitelist";
import { ProjectTagType, tagsPerProject } from "@/api/github/project-tags";

export interface ProjectMeta {
  type: "github";
  url: string;
  title: string;
  githubFullName: GithubWhiteListedRepository;
  description: string;
  githubForksCount: number;
  githubStars: number;
  /** If defined, link title to this URL. */
  href?: string;
}

interface ProjectCardProps {
  meta: ProjectMeta;
}

export const ProjectCard: FunctionComponent<ProjectCardProps> = ({ meta }) => {
  const tags = useMemo<readonly ProjectTagType[]>(
    () => tagsPerProject[meta.githubFullName] ?? [],
    [meta.githubFullName],
  );
  return (
    <div className="flex flex-col items-start justify-around border border-gray-lighter p-3 md:rounded-lg">
      {meta.href ? (
        <ExternalLink href={meta.href}>
          <h2 className="border-b-2 border-lychee text-lg font-bold">{meta.title}</h2>
        </ExternalLink>
      ) : (
        <h2 className="border-b-2 border-lychee text-lg font-bold">{meta.title}</h2>
      )}
      <p className="py-5 text-sm">{meta.description}</p>
      <div className="flex w-full flex-wrap items-center py-2">
        {tags.map(tag => (
          <ProjectTag key={tag} tag={tag} className="mr-2 last:mr-0" />
        ))}
      </div>
      <div className="flex w-full items-center justify-between text-sm">
        <div className="rounded-sm font-bold hover:text-lychee">
          <ExternalLink href={meta.url}>View on GitHub</ExternalLink>
        </div>
        <div className="flex items-center font-semibold">
          {meta.githubForksCount > 0 && (
            <p className="mr-4 text-orange">
              {meta.githubForksCount} fork{meta.githubForksCount > 1 ? "s" : ""}
            </p>
          )}
          {meta.githubStars > 0 && (
            <p className="text-yellow">
              {meta.githubStars} star{meta.githubStars > 1 ? "s" : ""}
            </p>
          )}
        </div>
      </div>
    </div>
  );
};
