// src/lib/VideoPlayer.svelte
<script lang="ts">
  // TODO: transform into working remark/rehype Mdsvex plugin
  export let src: string;
  export let title: string;
</script>

<video {src} {title} playsinline autoplay muted loop class="video-player" />

<style lang="postcss">
  .video-player {
    @apply w-full max-h-full;
  }
</style>

// src/components/blog/VideoPlayer.tsx
// TODO: maybe setup into working remark/rehype Mdsvex plugin

import { FunctionComponent } from "react";

interface VideoPlayerProps {
  src: string;
  title: string;
}

export const VideoPlayer: FunctionComponent<VideoPlayerProps> = ({ src, title }) => (
  <video src={src} title={title} playsInline autoPlay muted loop className="max-h-full w-full" />
);
