// src/components/blog/lsystem/LSystemControllableTracingRenderer.tsx
import { FunctionComponent, useMemo, useState } from "react";

import { LSystemTracingRenderer } from "./LSystemTracingRenderer";
import { LSystem, LSystemTrace, iteratedLSystem, traceLSystem } from "@/content/lsystem/lsystem";
import { LSystemScaleSlider } from "./LSystemScaleSlider";

interface LSystemControllableTracingRendererProps {
  lsystem: LSystem<string>;
  initialAngle: number;
  initialGeneration: number;
  // controls
  minGeneration: number;
  maxGeneration: number;
  // renderer controls
  scale: number;
  strokeWidthScale: (generation: number) => number;
  strokeColor: string;
}

export const LSystemControllableTracingRenderer: FunctionComponent<LSystemControllableTracingRendererProps> = ({
  lsystem,
  initialAngle = 0,
  initialGeneration = 2,
  minGeneration = 0,
  maxGeneration = 6,
  scale = 1.0,
  strokeWidthScale,
  strokeColor = "#141416",
}) => {
  const [forGeneration, setForGeneration] = useState(initialGeneration);
  const [statesPerGeneration, setStatesPerGeneration] = useState<Record<number, string>>({});
  const lsystemTrace = useMemo((): LSystemTrace => {
    let currentLSystem = { ...lsystem };
    const currentStatesPerGeneration: Record<number, string> = { ...statesPerGeneration };
    for (let currentGeneration = 0; currentGeneration <= forGeneration; currentGeneration++) {
      if (!statesPerGeneration[currentGeneration]) {
        currentStatesPerGeneration[currentGeneration] = iteratedLSystem(currentLSystem);
      }
      currentLSystem.generation = currentGeneration;
      currentLSystem.state = currentStatesPerGeneration[currentGeneration];
    }
    setStatesPerGeneration(currentStatesPerGeneration);
    return traceLSystem(currentLSystem, initialAngle);
  }, [lsystem, forGeneration, initialAngle]);

  const strokeWidth = useMemo(() => strokeWidthScale(forGeneration), [strokeWidthScale, forGeneration]);

  return (
    <div>
      <div>
        <span className="mb-2">Generation:&nbsp;</span>
        <LSystemScaleSlider
          initialValue={forGeneration}
          value={forGeneration}
          onChange={setForGeneration}
          min={minGeneration}
          max={maxGeneration}
          // step={Math.round(maxGeneration / (minGeneration + 1))}
        />
      </div>
      <div className="mt-6">
        <LSystemTracingRenderer
          trace={lsystemTrace}
          scale={scale}
          strokeWidth={strokeWidth}
          strokeColor={strokeColor}
          showGenerationLabel={false}
        />
      </div>
    </div>
  );
};

// src/lib/lsystems/LSystemControllableTracingRenderer.svelte
<script lang="ts">
  // documentation: https://simeydotme.github.io/svelte-range-slider-pips/
  import RangeSlider from "svelte-range-slider-pips";

  import LSystemTracingRenderer from "./LSystemTracingRenderer.svelte";
  import { iteratedLSystem, LSystem, LSystemTrace, traceLSystem } from "./lsystem";

  export let lsystem: LSystem<string>;
  export let initialAngle: number = 0;
  // controls
  export let minGeneration: number = 0;
  export let maxGeneration: number = 6;
  // renderer controls
  export let scale: number = 1.0;
  export let strokeWidthScale: (generation: number) => number;
  export let strokeColor: string = "#141416";

  export let initialGeneration: number = 2;
  let forGeneration = initialGeneration;

  const statesPerGeneration: Record<number, string> = {};

  // TODO: debouncing?
  $: currentLSystemTrace = ((): LSystemTrace => {
    let currentLSystem = { ...lsystem };
    for (let currentGeneration = 0; currentGeneration <= forGeneration; currentGeneration++) {
      if (!statesPerGeneration[currentGeneration]) {
        statesPerGeneration[currentGeneration] = iteratedLSystem(currentLSystem);
      }
      currentLSystem.generation = currentGeneration;
      currentLSystem.state = statesPerGeneration[currentGeneration];
    }
    return traceLSystem(currentLSystem, initialAngle);
  })();
  $: strokeWidth = strokeWidthScale(forGeneration);
</script>

<div class="container">
  <div class="controls-container">
    <span class="control-label">Generation: </span>
    <RangeSlider
      float
      range="min"
      pips
      all="label"
      pipstep={Math.round(maxGeneration / (minGeneration + 1))}
      min={minGeneration}
      max={maxGeneration}
      step={1}
      values={[forGeneration]}
      on:change={event => {
        forGeneration = event.detail?.value ?? initialGeneration;
      }}
      springValues={{ stiffness: 1, damping: 1 }}
    />
  </div>
  <div class="viewer">
    <LSystemTracingRenderer
      trace={currentLSystemTrace}
      {scale}
      {strokeWidth}
      {strokeColor}
      showGenerationLabel={false}
    />
  </div>
</div>

<style lang="postcss">
  .container {
    .viewer {
      @apply mt-6;
    }

    :global(.rangeSlider .pipVal) {
      @apply text-white;
    }
  }
</style>
