// src/components/blog/lsystem/LSystemTracingRenderer.tsx
import { select } from "d3-selection";
import { FunctionComponent, useEffect, useMemo, useRef } from "react";

import { LSystemTrace } from "@/content/lsystem/lsystem";

const LSYSTEM_STATE_DISPLAY_CUTOFF = 50;

interface LSystemTracingRendererProps {
  trace: LSystemTrace;
  // rendering parameters
  scale: number;
  strokeWidth: number;
  strokeColor: string;
  showCurrentState?: boolean;
  showGenerationLabel?: boolean;
}

export const LSystemTracingRenderer: FunctionComponent<LSystemTracingRendererProps> = ({
  trace,
  scale = 1.0,
  strokeWidth = 0.0075,
  strokeColor = "#141416",
  showCurrentState = false,
  showGenerationLabel = false,
}) => {
  const shortenedState = useMemo(
    () =>
      trace.forState.length > LSYSTEM_STATE_DISPLAY_CUTOFF
        ? `${trace.forState.substring(0, LSYSTEM_STATE_DISPLAY_CUTOFF)} ...`
        : trace.forState,
    [trace.forState],
  );

  const svgRef = useRef<SVGSVGElement>(null);
  useEffect(() => {
    if (!svgRef) {
      return;
    }
    const svg = select(svgRef.current);

    // cleanup
    svg.selectAll("*").remove();

    // SVG path elements
    const line = new Array<string>(trace.positions.length);
    for (const [i, { x, y }] of trace.positions.entries()) {
      const type = i === 0 ? "M" : "L";
      line[i] = `${type}${x * scale},${y * scale}`;
    }

    // viewport
    svg
      .attr("viewBox", [0, 0, trace.width * scale, trace.height * scale].join(" "))
      .style("height", `${(100 * trace.height) / trace.width}%`);

    // SVG path
    svg
      .append("path")
      .attr("d", line.join(", "))
      .attr("stroke", strokeColor)
      .attr("stroke-width", strokeWidth)
      .attr("fill", "none");
  }, [trace]);

  return (
    <div className="lsystem-renderer-container">
      {showCurrentState && (
        <div className="meta">
          <span className="label">State:&nbsp;</span>
          {shortenedState}
        </div>
      )}
      {showGenerationLabel && (
        <div className="meta">
          <span className="label">Generation:&nbsp;</span>
          {trace.forGeneration}
        </div>
      )}
      <svg ref={svgRef} />
    </div>
  );
};

// src/lib/lsystems/LSystemTracingRenderer.svelte
<script lang="ts">
  import { beforeUpdate } from "svelte";
  import { select } from "d3-selection";
  import type { LSystemTrace } from "./lsystem";

  // L-System trace
  export let trace: LSystemTrace;
  // rendering parameters
  export let scale: number = 1.0;
  export let strokeWidth: number = 0.0075;
  export let strokeColor: string = "#141416";
  export let showCurrentState: boolean = false;
  export let showGenerationLabel: boolean = false;

  let svgEl: SVGSVGElement;

  beforeUpdate(() => {
    if (!svgEl) {
      return;
    }
    const svg = select(svgEl);
    svg.selectAll("*").remove();

    // svg path elements
    const line = [];
    for (const [i, { x, y }] of trace.positions.entries()) {
      const type = i === 0 ? "M" : "L";
      line.push(`${type}${x * scale},${y * scale}`);
    }

    // viewport
    svg
      .attr("viewBox", [0, 0, trace.width * scale, trace.height * scale].join(" "))
      .style("height", `${(100 * trace.height) / trace.width}%`);

    // assembly
    svg
      .append("path")
      .attr("d", line.join(", "))
      .attr("stroke", strokeColor)
      .attr("stroke-width", strokeWidth)
      .attr("fill", "none");
  });

  const LSYSTEM_STATE_DISPLAY_CUTOFF = 50;
  $: shortenedState =
    trace.forState.length > LSYSTEM_STATE_DISPLAY_CUTOFF
      ? `${trace.forState.substring(0, LSYSTEM_STATE_DISPLAY_CUTOFF)} ...`
      : trace.forState;
</script>

<div class="container">
  {#if showCurrentState}
    <p class="meta">
      <span class="label">State: </span>
      {shortenedState}
    </p>
  {/if}
  {#if showGenerationLabel}
    <p class="meta">
      <span class="label">Generation: </span>
      {trace.forGeneration}
    </p>
  {/if}
  <svg bind:this={svgEl} />
</div>

<style lang="postcss">
  .container {
    @apply rounded p-3 bg-white text-black;
    .meta {
      @apply hidden w-full items-center justify-center;
      &:last-of-type {
        @apply mb-4;
      }
      .label {
        @apply text-gray-lighter;
        @apply mr-2;
      }
    }
  }

  @screen md {
    .container {
      .meta {
        @apply flex;
      }
    }
  }
</style>
